filter_naninf_points: true
filter_nearby_box_points: true
roi_x_min: 0.0
roi_x_max: 100.0
roi_y_min: -20.0
roi_y_max: 20.0
roi_z_max: 1.5

vehicle_x_min: -3.0
vehicle_x_max: 3.0
vehicle_y_min: -3.0
vehicle_y_max: 3.0
